/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    productions: Production
    media: Media
    users: User
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    productions: ProductionsSelect<false> | ProductionsSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences':
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    'payload-migrations':
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('ru' | 'en' | 'de')
    | ('ru' | 'en' | 'de')[]
  globals: {
    about: About
    contact: Contact
  }
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>
    contact: ContactSelect<false> | ContactSelect<true>
  }
  locale: 'ru' | 'en' | 'de'
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * Roman's productions. Slug is the public URL segment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions".
 */
export interface Production {
  id: number
  /**
   * Folder name in content/productions/ (lowercase, dashes). Don't change after publish — it's the live URL.
   */
  slug: string
  /**
   * Premiere year. Used for sort and display.
   */
  year?: number | null
  /**
   * Performance length in minutes, incl. intermission.
   */
  durationMin?: number | null
  status?: ('live' | 'in-development' | 'archived' | 'on-tour') | null
  /**
   * Title, tagline, synopsis, director's note, and full body.
   */
  identity: {
    /**
     * Production title. Localized.
     */
    title: string
    tagline?: string | null
    synopsis?: string | null
    /**
     * Quote from Roman, rendered italic. Supports markdoc (italic, links).
     */
    directorsNote?: string | null
    /**
     * Full editorial body. Markdown / markdoc.
     */
    body?: string | null
  }
  media?: {
    poster?: {
      src?: string | null
      credit?: string | null
    }
    productionsPhoto?: {
      src?: string | null
      credit?: string | null
    }
    featuredPhoto?: {
      src?: string | null
      credit?: string | null
    }
    gallery?:
      | {
          src?: string | null
          credit?: string | null
          caption?: string | null
          id?: string | null
        }[]
      | null
    videos?:
      | {
          provider?: ('youtube' | 'vimeo') | null
          id?: string | null
        }[]
      | null
  }
  production?: {
    theatre?: {
      name?: string | null
      shortName?: string | null
      city?: string | null
      /**
       * ISO-2 code: RU / KZ / DE / AT / ES.
       */
      country?: string | null
      url?: string | null
      year?: number | null
    }
    premiereDate?: string | null
    ticketsUrl?: string | null
    /**
     * Russian-standard age rating: 0+, 6+, 12+, 16+, 18+.
     */
    ageRating?: string | null
  }
  taxonomy?: {
    role?:
      | (
          | 'director'
          | 'co-director'
          | 'performer'
          | 'art-director'
          | 'playwright'
          | 'producer'
        )[]
      | null
    /**
     * Genre / form. Free-form: solo, puppet, family, festival.
     */
    form?:
      | {
          value?: string | null
          id?: string | null
        }[]
      | null
    /**
     * School / tradition. Free-form: btk, kudashov, rgisi.
     */
    lineage?:
      | {
          value?: string | null
          id?: string | null
        }[]
      | null
    tags?:
      | {
          value?: string | null
          id?: string | null
        }[]
      | null
  }
  team?: {
    creditsRu?:
      | {
          role?: string | null
          name?: string | null
          url?: string | null
          id?: string | null
        }[]
      | null
    creditsEn?:
      | {
          role?: string | null
          name?: string | null
          url?: string | null
          id?: string | null
        }[]
      | null
    creditsDe?:
      | {
          role?: string | null
          name?: string | null
          url?: string | null
          id?: string | null
        }[]
      | null
  }
  recognition?: {
    awards?:
      | {
          name?: string | null
          year?: number | null
          category?: string | null
          city?: string | null
          url?: string | null
          id?: string | null
        }[]
      | null
    festivals?:
      | {
          name?: string | null
          year?: number | null
          category?: string | null
          city?: string | null
          id?: string | null
        }[]
      | null
    press?:
      | {
          title?: string | null
          url?: string | null
          outlet?: string | null
          /**
           * Language code: ru / en / de.
           */
          language?: string | null
          id?: string | null
        }[]
      | null
    externalLinks?:
      | {
          label?: string | null
          url?: string | null
          id?: string | null
        }[]
      | null
  }
  history?: {
    tour?:
      | {
          city?: string | null
          id?: string | null
        }[]
      | null
    runs?:
      | {
          venue?: string | null
          city?: string | null
          yearFrom?: number | null
          yearTo?: number | null
          count?: string | null
          id?: string | null
        }[]
      | null
  }
  settings?: {
    /**
     * When off, the production page hides the booking CTA.
     */
    bookingCta?: boolean | null
    bookingCtaLabel?: string | null
    bookingCtaUrl?: string | null
    /**
     * Surface this production on the home featured strip.
     */
    featured?: boolean | null
    featuredOrder?: number | null
    listOrder?: number | null
    techRider?: string | null
    pressKit?: string | null
    /**
     * Legacy Notion CMS IDs. Read-only in spirit.
     */
    notionIds?: {
      ru?: string | null
      en?: string | null
    }
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  /**
   * Accessibility / SEO alt text, per locale.
   */
  alt?: string | null
  /**
   * Photographer credit.
   */
  credit?: string | null
  prefix?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  /**
   * Display name shown in the admin header.
   */
  name?: string | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'productions'
        value: number | Production
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productions_select".
 */
export interface ProductionsSelect<T extends boolean = true> {
  slug?: T
  year?: T
  durationMin?: T
  status?: T
  identity?:
    | T
    | {
        title?: T
        tagline?: T
        synopsis?: T
        directorsNote?: T
        body?: T
      }
  media?:
    | T
    | {
        poster?:
          | T
          | {
              src?: T
              credit?: T
            }
        productionsPhoto?:
          | T
          | {
              src?: T
              credit?: T
            }
        featuredPhoto?:
          | T
          | {
              src?: T
              credit?: T
            }
        gallery?:
          | T
          | {
              src?: T
              credit?: T
              caption?: T
              id?: T
            }
        videos?:
          | T
          | {
              provider?: T
              id?: T
            }
      }
  production?:
    | T
    | {
        theatre?:
          | T
          | {
              name?: T
              shortName?: T
              city?: T
              country?: T
              url?: T
              year?: T
            }
        premiereDate?: T
        ticketsUrl?: T
        ageRating?: T
      }
  taxonomy?:
    | T
    | {
        role?: T
        form?:
          | T
          | {
              value?: T
              id?: T
            }
        lineage?:
          | T
          | {
              value?: T
              id?: T
            }
        tags?:
          | T
          | {
              value?: T
              id?: T
            }
      }
  team?:
    | T
    | {
        creditsRu?:
          | T
          | {
              role?: T
              name?: T
              url?: T
              id?: T
            }
        creditsEn?:
          | T
          | {
              role?: T
              name?: T
              url?: T
              id?: T
            }
        creditsDe?:
          | T
          | {
              role?: T
              name?: T
              url?: T
              id?: T
            }
      }
  recognition?:
    | T
    | {
        awards?:
          | T
          | {
              name?: T
              year?: T
              category?: T
              city?: T
              url?: T
              id?: T
            }
        festivals?:
          | T
          | {
              name?: T
              year?: T
              category?: T
              city?: T
              id?: T
            }
        press?:
          | T
          | {
              title?: T
              url?: T
              outlet?: T
              language?: T
              id?: T
            }
        externalLinks?:
          | T
          | {
              label?: T
              url?: T
              id?: T
            }
      }
  history?:
    | T
    | {
        tour?:
          | T
          | {
              city?: T
              id?: T
            }
        runs?:
          | T
          | {
              venue?: T
              city?: T
              yearFrom?: T
              yearTo?: T
              count?: T
              id?: T
            }
      }
  settings?:
    | T
    | {
        bookingCta?: T
        bookingCtaLabel?: T
        bookingCtaUrl?: T
        featured?: T
        featuredOrder?: T
        listOrder?: T
        techRider?: T
        pressKit?: T
        notionIds?:
          | T
          | {
              ru?: T
              en?: T
            }
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  credit?: T
  prefix?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number
  /**
   * Biography. Markdown / markdoc. First paragraph is the lead.
   */
  body?: string | null
  portrait?: {
    src?: string | null
    credit?: string | null
  }
  photos?:
    | {
        src?: string | null
        credit?: string | null
        id?: string | null
      }[]
    | null
  milestones?:
    | {
        year?: number | null
        label?: string | null
        id?: string | null
      }[]
    | null
  lineage?:
    | {
        key?: string | null
        name?: string | null
        role?: string | null
        institution?: string | null
        note?: string | null
        id?: string | null
      }[]
    | null
  marginalia?:
    | {
        note?: string | null
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number
  /**
   * Optional intro paragraph above the contact buttons.
   */
  intro?: string | null
  email: string
  telegramUrl?: string | null
  instagramUrl?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  body?: T
  portrait?:
    | T
    | {
        src?: T
        credit?: T
      }
  photos?:
    | T
    | {
        src?: T
        credit?: T
        id?: T
      }
  milestones?:
    | T
    | {
        year?: T
        label?: T
        id?: T
      }
  lineage?:
    | T
    | {
        key?: T
        name?: T
        role?: T
        institution?: T
        note?: T
        id?: T
      }
  marginalia?:
    | T
    | {
        note?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  intro?: T
  email?: T
  telegramUrl?: T
  instagramUrl?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
