In the most ordinary forest, among the most typical animals, lives a not-quite-ordinary Bear.
What is wrong with him? After all, like all his shaggy relatives, he loves sweet things (and generally eating), sleeping longer, warming up in the sun…
When they look at him, why do the neighbors keep sighing: “Bear is in his repertoire!”? Maybe it's because he's a spectacled *bear*, which means he's a bit more 'bearish'? Or is it that he likes listening to the radio, almost more than eating, and everything interests him? Sometimes he's learning to fly, sometimes singing, sometimes making friends with a flower on his lapel…
How does he live, so strangely? Is it easy for him to be alone? And with him, so unusual?
